
package com.petmanager.views;

import com.petmanager.controllers.Coordinator;
import java.awt.Image;
import javax.swing.*;

public class MainView extends javax.swing.JFrame{

    private Coordinator myCoordinator;
    
    public void setCoordinator(Coordinator coordinator){
        this.myCoordinator = coordinator;    
    }
    
    public MainView() {
        initComponents();
        setSize(1024,640);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Escalar imagen al iniciar
        resizeImage();
        
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                resizeImage();
            }
        });
    }

    private void resizeImage() {
        // Cargar icono original
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/petmanager/images/bgPet.png"));
        // Obtener la imagen
        Image img = icon.getImage();
        // Redimensionar
        Image scaled = img.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
        // Establecer en el JLabel
        image.setIcon(new ImageIcon(scaled));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        h1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        registerPet = new javax.swing.JButton();
        findPet = new javax.swing.JButton();
        findAllPets = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 640));
        setMinimumSize(new java.awt.Dimension(1024, 640));

        background.setBackground(new java.awt.Color(36, 101, 171));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        h1.setFont(new java.awt.Font("Bebas Neue", 1, 48)); // NOI18N
        h1.setForeground(new java.awt.Color(255, 255, 255));
        h1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h1.setText("Administrador de mascotas");
        background.add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/petmanager/images/bgPet.png"))); // NOI18N
        image.setMaximumSize(new java.awt.Dimension(512, 640));
        image.setMinimumSize(new java.awt.Dimension(512, 640));
        image.setPreferredSize(new java.awt.Dimension(512, 640));
        background.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 512, 640));

        subtitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitle.setForeground(new java.awt.Color(255, 255, 255));
        subtitle.setText("Menún principal");
        background.add(subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 180, 40));

        registerPet.setBackground(new java.awt.Color(65, 136, 220));
        registerPet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerPet.setForeground(new java.awt.Color(255, 255, 255));
        registerPet.setText("REGISTRAR MASCOTA");
        registerPet.setBorder(null);
        registerPet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPetActionPerformed(evt);
            }
        });
        background.add(registerPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 220, 40));

        findPet.setBackground(new java.awt.Color(65, 136, 220));
        findPet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        findPet.setForeground(new java.awt.Color(255, 255, 255));
        findPet.setText("BUSCAR MASCOTA");
        findPet.setBorder(null);
        findPet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        findPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findPetActionPerformed(evt);
            }
        });
        background.add(findPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 220, 40));

        findAllPets.setBackground(new java.awt.Color(65, 136, 220));
        findAllPets.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        findAllPets.setForeground(new java.awt.Color(255, 255, 255));
        findAllPets.setText("VER LISTA DE MASCOTAS");
        findAllPets.setBorder(null);
        findAllPets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        findAllPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findAllPetsActionPerformed(evt);
            }
        });
        background.add(findAllPets, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPetActionPerformed
        if(evt.getSource() == registerPet){
            this.setVisible(false);
            myCoordinator.showRegisterView();
        }
    }//GEN-LAST:event_registerPetActionPerformed

    private void findPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findPetActionPerformed
        if(evt.getSource() == findPet){
            myCoordinator.showQueryPetView();
        }
    }//GEN-LAST:event_findPetActionPerformed

    private void findAllPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findAllPetsActionPerformed
        if(evt.getSource() == findAllPets){
            myCoordinator.showQueryListPetView();
        }
    }//GEN-LAST:event_findAllPetsActionPerformed

    public void setMyCoordinator(Coordinator myCoordinator){
        this.myCoordinator = myCoordinator;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton findAllPets;
    private javax.swing.JButton findPet;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel image;
    private javax.swing.JButton registerPet;
    private javax.swing.JLabel subtitle;
    // End of variables declaration//GEN-END:variables
}
