/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.petmanager.views;

import com.petmanager.controllers.Coordinator;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author mvarg
 */
public class QueryPetView extends javax.swing.JFrame {

    private Coordinator myCoordinator;

    
    public QueryPetView() {
        initComponents();
        setSize(1024,640);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
        // Escalar imagen al iniciar
        resizeImage();
        
        // Agregar listener para que se reescale cuando se cambia el tamaño
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                resizeImage();
            }
        });
    }

    /**
     * Método para reescalar la imagen del JLabel
     */
    private void resizeImage() {
        // Cargar icono original
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/petmanager/images/bgPet.png"));
        // Obtener la imagen
        Image img = icon.getImage();
        // Redimensionar
        Image scaled = img.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
        // Establecer en el JLabel
        image.setIcon(new ImageIcon(scaled));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        h1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        lblNumId = new javax.swing.JLabel();
        find = new javax.swing.JButton();
        subtitle = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));

        background.setBackground(new java.awt.Color(36, 101, 171));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        h1.setFont(new java.awt.Font("Bebas Neue", 1, 48)); // NOI18N
        h1.setForeground(new java.awt.Color(255, 255, 255));
        h1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h1.setText("Administrador de mascotas");
        background.add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/petmanager/images/bgPet.png"))); // NOI18N
        image.setMaximumSize(new java.awt.Dimension(512, 640));
        image.setMinimumSize(new java.awt.Dimension(512, 640));
        image.setPreferredSize(new java.awt.Dimension(512, 640));
        background.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 512, 640));

        lblNumId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNumId.setForeground(new java.awt.Color(255, 255, 255));
        lblNumId.setText("Número de Identificacion");
        background.add(lblNumId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 220, 20));

        find.setBackground(new java.awt.Color(65, 136, 220));
        find.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        find.setForeground(new java.awt.Color(255, 255, 255));
        find.setText("BUSCAR");
        find.setBorder(null);
        find.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        background.add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 350, 40));

        subtitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        subtitle.setForeground(new java.awt.Color(255, 255, 255));
        subtitle.setText("Buscar mascota");
        background.add(subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 180, 40));
        background.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 350, 40));

        volver.setBackground(new java.awt.Color(65, 136, 220));
        volver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.setBorder(null);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        background.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        
    }//GEN-LAST:event_findActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.dispose();
        myCoordinator.showMainView();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setMyCoordinator(Coordinator myCoordinator){
        this.myCoordinator = myCoordinator;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JPanel background;
    private javax.swing.JButton find;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel image;
    private javax.swing.JLabel lblNumId;
    private javax.swing.JLabel subtitle;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
