package com.petmanager.views;

import com.petmanager.controllers.Coordinator;
import com.petmanager.models.dao.PetDao;
import com.petmanager.models.dto.Pet;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author mvarg
 */
public class QueryListPetView extends javax.swing.JFrame {
    
    private Coordinator myCoordinator;
    private PetDao listPets;


    /**
     * Creates new form MainView
     */
    public QueryListPetView() {
        initComponents();
        setSize(1024,640);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Escalar imagen al iniciar
        resizeImage();
        
        // Agregar listener para que se reescale cuando se cambia el tamaño
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                resizeImage();
            }
        });
    }
    
    private void resizeImage() {
        // Cargar icono original
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/petmanager/images/bgPet.png"));
        // Obtener la imagen
        Image img = icon.getImage();
        // Redimensionar
        Image scaled = img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        // Establecer en el JLabel
        jLabel3.setIcon(new ImageIcon(scaled));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        findAllbySex = new javax.swing.JButton();
        scrollBoard = new javax.swing.JScrollPane();
        petBoard = new javax.swing.JTable();
        volver = new javax.swing.JButton();
        jComboBoxSex = new javax.swing.JComboBox<>();
        findAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 640));

        background.setBackground(new java.awt.Color(36, 101, 171));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administrador de mascotas");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/petmanager/images/bgPet.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(512, 640));
        jLabel3.setMinimumSize(new java.awt.Dimension(512, 640));
        jLabel3.setPreferredSize(new java.awt.Dimension(512, 640));
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 512, 640));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LISTADO DE MASCOTAS");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 220, 40));

        findAllbySex.setBackground(new java.awt.Color(65, 136, 220));
        findAllbySex.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        findAllbySex.setForeground(new java.awt.Color(255, 255, 255));
        findAllbySex.setText("MOSTRAR POR SEXO");
        findAllbySex.setBorder(null);
        findAllbySex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        findAllbySex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findAllbySexActionPerformed(evt);
            }
        });
        background.add(findAllbySex, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 210, 40));

        petBoard.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        petBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Sexo", "Color", "Raza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollBoard.setViewportView(petBoard);

        background.add(scrollBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 280));

        volver.setBackground(new java.awt.Color(65, 136, 220));
        volver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.setBorder(null);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        background.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 40));

        jComboBoxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR SEXO", "MACHO", "HEMBRA" }));
        background.add(jComboBoxSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 210, -1));

        findAll.setBackground(new java.awt.Color(65, 136, 220));
        findAll.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        findAll.setForeground(new java.awt.Color(255, 255, 255));
        findAll.setText("MOSTRAR MASCOTAS");
        findAll.setBorder(null);
        findAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        findAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findAllActionPerformed(evt);
            }
        });
        background.add(findAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findAllbySexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findAllbySexActionPerformed
        findBySex();
    }//GEN-LAST:event_findAllbySexActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.dispose();
        myCoordinator.showMainView();
    }//GEN-LAST:event_volverActionPerformed

    private void findAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findAllActionPerformed
        findAll();
    }//GEN-LAST:event_findAllActionPerformed

    private void findBySex(){
        String selectSex = jComboBoxSex.getSelectedItem().toString();
		List<Pet> listPets = myCoordinator.queryPetSex(selectSex);
		if (listPets.size() > 0) {
			fillBoard(listPets);
		} else {
			JOptionPane.showMessageDialog(null, "No hay mascotas con sexo " + selectSex);
		}
    }
    
    private void findAll(){
        List<Pet> listPets = myCoordinator.queryListPet(null);
        
	if (listPets.size() > 0) {
            fillBoard(listPets);

	} else {
            JOptionPane.showMessageDialog(null, "No hay mascotas ");
	}
    }
    
    private void fillBoard(List<Pet> listPets){
        
        String columnsName [] = { "Identificacion", "Nombre", "Sexo", "Color", "Raza" };

		String info[][] = new String[listPets.size()][5];

		for (int x = 0; x < listPets.size(); x++) {
			info[x][0] = String.valueOf(listPets.get(x).getPetId());
			info[x][1] = listPets.get(x).getName();
			info[x][2] = listPets.get(x).getBreed();
			info[x][3] = listPets.get(x).getColor();
			info[x][4] = listPets.get(x).getSex();
		}

		petBoard = new JTable(info, columnsName);
		scrollBoard.setViewportView(petBoard);

		int[] anchos = { 50, 120, 120, 120, 80 };
		for (int i = 0; i < petBoard.getColumnCount(); i++) {
			petBoard.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
		}
    }
    
    
    
    public void setMyCoordinator(Coordinator myCoordinator){
        this.myCoordinator = myCoordinator;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton findAll;
    private javax.swing.JButton findAllbySex;
    private javax.swing.JComboBox<String> jComboBoxSex;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTable petBoard;
    private javax.swing.JScrollPane scrollBoard;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
